version: "3"

services:

    machine:
        container_name: image_classifier
        restart: always
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - "6006:6006"
        env_file: "setup/.env[MODEL]"
        volumes:
            - type: bind
              source: ./model
              target: /usr/app/model
            - type: bind
              source: ./logs
              target: /usr/app/logs
        command: tensorboard --bind_all --logdir /usr/app/logs/fit
        #command: python3 app.py
        #command: gunicorn platform_rest.wsgi --bind 0.0.0.0:80 --workers 2   #- "80:80"


volumes:
    model:
    logs:

